; PlatformIO Project Configuration File
[platformio]
description = A2DP Example
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps = 
    https://github.com/pschatzmann/ESP32-A2DP.git
    https://github.com/pschatzmann/arduino-audio-tools.git
    https://github.com/pschatzmann/arduino-libmad.git
    https://github.com/adafruit/Adafruit-GFX-Library.git
    https://github.com/adafruit/Adafruit-ST7735-Library.git
build_flags = -DCORE_DEBUG_LEVEL=2 
board_build.partitions = huge_app.csv
monitor_speed = 115200
monitor_filters = esp32_exception_decoder